### PR TITLE
Add ZeroizeOnDrop support for Strobe.

### PR DESCRIPTION
**Pull request by codahale**
This adds a derived `ZeroizeOnDrop` implementation for `Strobe`, allowing for the state to be securely erased in memory once an instance is dropped.

### CODE REVIEW

**Comment by rozbb** [comment]
Hi, I apologize for the delay. This is great! Do you think it'd be possible to also impl `Zeroize` on `OpFlags` as well, just for the sake of completion (that way it doesn't have to be `#[zeroize(skip)]`'d)? The protocol state of a `STROBE` session might be considered just as private as the sponge state.

**Comment by codahale** [comment]
Good point. The derive macro doesn’t play nice with bitflags, so I added a concrete impl for Zeroize.

**Comment by rozbb** [comment]
Fantastic, thank you!

**Comment by codahale** [comment]
Thanks for writing and maintaining this library!

**Pull request merged**
